apiVersion: v1
kind: Secret
metadata:
  name: {{ include "analytics-agent.fullname" . }}-env
  labels:
    {{- include "analytics-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.config.env }}
  {{ $key }}: {{ tpl (toString $value) $ | quote }}
  {{- end }}
