export const STARTER_PROMPTS: string[] = [
  // Revenue & growth
  "Which customers are basically paying our office rent right now?",
  "Show me where we're leaving money on the table…",
  "What does revenue look like if we pretend our top 3 accounts never existed?",
  "Which product lines are quietly crushing it while nobody's watching?",
  "Is growth coming from new logos or are our existing customers just loving us more?",
  "Who had the biggest glow-up in revenue this quarter?",
  "Find me the fastest-growing cohort from the last 6 months.",
  "Which segments are punching way above their weight?",
  "Show me the revenue story I should be telling at the next board meeting.",
  "What would happen to ARR if we cut churn in half?",
  "Show me which industries are sending us the most money right now.",
  "Which pricing tier is growing like a weed?",
  "Find the revenue trend that nobody on the team is talking about yet.",
  "Which new logos from last quarter are already looking like keepers?",
  "Show me a waterfall chart of where we gained and lost revenue this quarter.",

  // Churn & retention
  "Who's about to break up with us and doesn't know how to say it yet?",
  "Which accounts ghosted us this quarter?",
  "What do our churned customers all have in common? Be brutally honest.",
  "Find the accounts that are one bad quarter away from leaving.",
  "Who renewed after we thought they were gone for good?",
  "What does the 12-month retention curve actually look like?",
  "Which customers are paying us but clearly checked out?",
  "Find the usage red flags that show up 60 days before churn.",
  "Which segments stick around the longest and why?",
  "Show me the accounts that downgraded but haven't left yet — they need attention.",
  "What's the median time between signup and first sign of disengagement?",
  "Find the customers who went cold in the last 30 days.",
  "Which onboarding steps actually predict whether someone stays?",
  "Show me gross churn vs. net churn — how bad is it really?",
  "Which customer segments have the best survival rates at 6 months?",

  // Usage & adoption
  "Which features are people actually using vs. which ones do we just love in demos?",
  "Where do new users vanish after their first week?",
  "Show me MAU for the past year — are we actually growing?",
  "What does a power user look like compared to someone who barely shows up?",
  "Which features have the worst adoption? Don't spare my feelings.",
  "Find the customers who are getting maximum value and figure out what they're doing.",
  "Which accounts are using everything we've built?",
  "Show me the stickiest parts of the product.",
  "What time of day is everyone actually online?",
  "Find the feature we built last year that finally hit its stride.",
  "Which features do our best customers use that nobody else touches?",
  "Show me how session length has trended over the last 6 months.",
  "What does the distribution of logins per user actually look like?",
  "Find the moment in onboarding where the product clicks for people.",
  "Which features launched in the last year are actually earning their keep?",

  // Customers & accounts
  "Who are our 10 most engaged customers right now?",
  "Which enterprise accounts haven't heard from sales in 90+ days?",
  "Find the customers who should be case studies but aren't yet.",
  "What does a customer look like right before they 3x their contract?",
  "Show me all new accounts from the last 30 days — who looks promising?",
  "Which customers have expanded the most times? Send them a thank-you note.",
  "Find the accounts that fit our ICP perfectly but are barely using us.",
  "What's the average deal size by industry? Any surprises?",
  "Which customers went from light users to power users this quarter?",
  "Show me new logos by month for the past year — is the curve going the right way?",
  "Find the customer segment we're accidentally ignoring.",
  "Which accounts are on old plans that we should really migrate?",
  "What's the profile of a customer who refers others to us?",
  "Show me customers by headcount vs. how much they actually use us.",
  "Find the account that would hurt the most to lose. Don't make me guess.",

  // AI & agent usage
  "Which customers are leaning into AI the hardest?",
  "Who are our top AI power users — they probably deserve a call.",
  "Show me AI usage trends over the last quarter. Is adoption real?",
  "What types of questions are people actually asking the AI?",
  "Which customers signed up for AI features and then went radio silent?",
  "Find the accounts where AI usage is climbing week over week.",
  "What percentage of active users have actually tried AI at least once?",
  "Show me which teams inside our customers are using AI most.",
  "Is there a correlation between AI adoption and contract renewal?",
  "Which customers adopted AI fastest — what do they have in common?",
  "Show me the distribution of AI session lengths.",
  "Find the customers who use AI daily. They're our biggest fans.",
  "What's the most common question type people ask the AI?",
  "Show me AI interaction volume vs. overall platform usage side by side.",
  "Which customers haven't touched AI yet? They're leaving value on the table.",

  // Operations & efficiency
  "Which queries are absolutely hammering our warehouse?",
  "Find the 20% of queries consuming 80% of our compute. Classic.",
  "Show me compute costs by team — who's being expensive?",
  "What's the average query time been doing over the last month?",
  "Find the scheduled jobs that always run the longest.",
  "Which data sources are dumping the most rows in per day?",
  "Show me query volume by hour — when does everything hit at once?",
  "Which analysts are running the most queries right now?",
  "Find the reports that get run constantly. Someone really loves them.",
  "What's our warehouse utilization looking like? Any waste to cut?",
  "Show me which departments are actually using data vs. just requesting it.",
  "Find the queries that have been running forever and never get optimized.",
  "Which tables get read nonstop but almost never written to?",
  "Show me error rates for our most important data jobs.",
  "What would it cost us if compute prices went up 20%?",

  // Product & strategy
  "What does the data say about whether we actually have product-market fit?",
  "Which features do customers who renew use vs. ones who churn?",
  "Show me time-to-value trends — are we getting people to the aha moment faster?",
  "Find the leading indicators that an account is about to expand.",
  "What does the journey from free to paid actually look like step by step?",
  "Which product bets from the last year are paying off?",
  "What's the adoption curve for our newest feature? Be honest.",
  "Find the usage pattern that reliably predicts a 2x expansion.",
  "Show me what actions new users take in their first 7 days that actually matter.",
  "Which customers are most likely to become public advocates for us?",
  "What does a genuinely healthy customer look like in the data?",
  "Find the product milestone that correlates most with 1-year retention.",
  "Show me feature usage broken down by company size.",
  "What's the average time from signup to first real outcome?",
  "Which features are in every power user's toolkit?",

  // People & teams
  "Which internal teams are the heaviest data consumers?",
  "Show me query activity by analyst this month — who's on fire?",
  "Find the team that would scream the loudest if the data platform went down.",
  "Which analysts are generating insights others actually use?",
  "Who's creating the most new reports and dashboards this quarter?",
  "Show me cross-team data sharing — are we a silo or a network?",
  "Find the people whose queries get borrowed by everyone else.",
  "Which business units are getting more data-driven over time?",
  "Show me data usage trends by department — where's the momentum?",
  "Which teams have the fastest turnaround from question to answer?",
  "Find the analysts running the most unique queries — they're probably curious.",
  "Who queries a ton but shares nothing? Time for a conversation.",
  "Which teams are asking the most interesting questions right now?",
  "Show me the spread of data savviness across departments.",
  "Find the person who's probably building a rogue spreadsheet somewhere.",

  // Trends & surprises
  "Surprise me with something interesting hiding in our data.",
  "What's the most counterintuitive thing the data is telling us right now?",
  "Find the trend that's about to become everyone's talking point.",
  "What would keep me up at night if I saw it?",
  "Show me what's quietly going right that we're not celebrating enough.",
  "Find the metric nobody's watching that everyone should be.",
  "What story is the data dying to tell but nobody's asked yet?",
  "Show me something that would make the CEO smile.",
  "Find the thing that's been climbing for 6 months with zero fanfare.",
  "What changed the most between last quarter and this one?",
  "Which metric is the best leading indicator that we're going to have a great year?",
  "Find the anomaly from the last 7 days I should probably know about.",
  "Show me a year-over-year comparison of our most important number.",
  "Which months have historically been our strongest? Any pattern?",
  "What does the data know that the team hasn't figured out yet?",

  // Competitive & market
  "Which accounts are we losing to competitors and what do they have in common?",
  "Show me win rates by deal size — where do we dominate?",
  "Find the deal profile we almost always close. Double down there.",
  "Which industries are we underpenetrated in but probably shouldn't be?",
  "Show me the average sales cycle by segment — where does it drag?",
  "Find the market segments where our win rate is trending the wrong way.",
  "Which competitors do we beat most often? What's the pattern?",
  "Show me where we're losing on price vs. where we're losing on product.",
  "Find the accounts that switched to us from a competitor — what convinced them?",
  "Show me pipeline coverage vs. quota for next quarter. Nervous yet?",
  "What's our win rate been doing over the last 4 quarters?",
  "Find the deal sizes where we need to get better.",
  "Which geographies are we winning in that we're not focused on enough?",
  "Show me conversion rates by lead source this quarter — any shockers?",
  "What does the profile of an easy win look like?",

  // Finance & forecasting
  "How confident should I actually be in the Q3 forecast?",
  "Show me the ARR bridge from last quarter — gains, losses, the whole story.",
  "What's our CAC payback period and is it getting better or worse?",
  "Find the deals most likely to slip out of this quarter before it's too late.",
  "Show me gross margin trends — are we getting more efficient?",
  "What's the LTV:CAC ratio by channel? Any obvious winners?",
  "Find the customers with expansion potential we haven't had a real conversation with.",
  "What would hitting 110% of plan require in the next 30 days?",
  "Show me our bookings pacing vs. plan right now. Deep breath.",
  "Which months historically close the most revenue? Plan accordingly.",
  "What's the distribution of deal sizes from last year — any surprises?",
  "Find the accounts that renewed but we probably should have paid more attention to.",
  "Show me cash burn vs. the milestones that actually matter.",
  "Which cost centers are growing faster than revenue? Call them out.",
  "What does the rule of 40 look like for us right now?",

  // Support & success
  "Which customers have a stack of open tickets we should probably fix?",
  "Find the support issues that almost always show up before someone churns.",
  "Which CSMs have the best retention rates? What are they doing differently?",
  "Show me NPS trends over the last four quarters — are we getting better?",
  "Find customers who complained loudly and then expanded anyway. Heroes.",
  "Which product areas are generating the most support pain?",
  "Show me CSAT by customer tier — any uncomfortable truths?",
  "Find the accounts that escalated more than twice this year.",
  "What are the top issues customers hit in their first 30 days?",
  "Which CSMs are carrying the most at-risk accounts right now? Help them.",
  "Show me average time-to-resolution by ticket type.",
  "Find the customers with perfect CSAT who still somehow churned.",
  "What does support ticket volume look like at the start of each week?",
  "Show me the correlation between support volume and contract value.",
  "Which issues get resolved fastest? We should do more of whatever that is.",

  // Marketing & pipeline
  "Which marketing channels are sending us the most valuable leads?",
  "Show me MQL to SQL conversion rates — where's the drop-off?",
  "Find the campaigns that are actually generating pipeline, not just clicks.",
  "Which lead sources have the fastest path to close?",
  "Show me free trial conversion by where the user came from.",
  "Find the top-of-funnel signals that reliably turn into revenue.",
  "Which events drove the most pipeline this year? Worth repeating?",
  "Show me attribution for last quarter's new ARR. Any surprises?",
  "Which industries convert fastest from first touch to closed-won?",
  "Find the landing pages with the best lead quality, not just volume.",
  "What's our average cost per qualified lead by channel?",
  "Show me the campaigns with the best 90-day pipeline payback.",
  "Which content is actually influencing deals vs. just getting traffic?",
  "Find the lead sources that look great on paper but never actually close.",
  "What does our pipeline look like for next quarter? Honest answer.",
];
